# Site settings
title: Why I Love The ASF
email: asf@shanecurcuru.org
description: > # this means to ignore newlines until "baseurl:"
  Why I Love The ASF: useful information and pointers to community
  resources about the Apache Software Foundation and the many
  Apache projects by long-time Member Shane Curcuru.
baseurl: "/whyilovetheasf/" # the subpath of your site, e.g. /blog/
url: "http://shanecurcuru.github.io" # the base hostname & protocol for your site
twitter_username: shanecurcuru
github_username:  ShaneCurcuru
permalink: none


# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# Custom UI settings
sister_sites:
  site1:
    name: Community Over Code
    link: communityovercode.com
  site2:
    name: What Is Hadoop?
    link: hadoop.biz
  site3:
    name: Punderings
    link: shane.curcuru.name/blog/

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

# Build settings
markdown: kramdown
