# Site settings
title: Why I Love The ASF
email: asfl@shanecurcuru.org
desctitle: RESPECT APACHE BRANDS
description: >
  Apache&reg; and all Apache project names are either registered trademarks
  or trademarks of the <a href="//www.apache.org/">Apache Software Foundation</a> (ASF) in the
  United States and/or other countries. The ASF has no affiliation with
  and does not endorse or review the materials provided at this website,
  which is managed by Shane Curcuru.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://whyilovetheasf.com" # the base hostname & protocol for your site
twitter_username: shanecurcuru
github_username:  ShaneCurcuru
permalink: none

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
paginate: 6

# Custom UI settings
sister_sites:
  site1:
    name: Community Over Code
    link: communityovercode.com
  site2:
    name: What Is Hadoop?
    link: hadoop.biz
  site3:
    name: Punderings
    link: shane.curcuru.name/blog/

# Build settings
markdown: kramdown
